#!/usr/bin/env python

from gcalcli import *

gcal = gcalcli(client_id='996124500222-lrv2poibi8ll15cg25s1bs8eu7atjfk2.apps.googleusercontent.com',
               client_secret='zmQliJX0STI81we6csuy5wzb',
               refreshCache=True)

def setCal(cal_name):
    matches = []
    for cal in gcal.allCals:
        if cal_name == cal['summary']:
            gcal.cals = [cal]
            return
    print ("ERROR! there is no such calendar as '" + cal_name + "'!")
    print ("Available:")
    gcal.ListAllCalendars()
    exit(1)

def removeByDescription(desc, start=None, end=None):
    ev_list = gcal._SearchForCalEvents(start, end, None)
    gcal.iamaExpert = True
    for ev in ev_list: 
        if desc in ev['description']:
            #print ev['summary']
            #gcal.iamaExpert = False
            gcal._DeleteEvent(ev)

def main():
    setCal('red');
    n, m = ParseReminder('30m popup')
    eStart, eEnd = GetTimeFromStr('3/28/2015 10:00', 60)
    gcal.ListAllCalendars()
    gcal.AddEvent("My test event", "NONE", eStart, eEnd, "_autogenerated_", [str(n) + ' ' + m])  
    removeByDescription("_autogenerated_")
    print datetime.now(tzlocal())
    print eStart

if __name__ == '__main__':
    main()
